version: 2
jobs:

  build:
    docker: [{ image: 'circleci/node:8.11.1-browsers' }]
    steps:
      - checkout
      - restore_cache: { key: 'npm-packages-{{ checksum "package-lock.json" }}' }
      - run: npm install
      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths: [ /root/project/node_modules ]
      - run: |
          URL=$(./node_modules/.bin/now --token "$NOW_TOKEN")
          ./node_modules/.bin/now alias "$URL" registry-demo --token "$NOW_TOKEN"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters: { tags: { only: /.*/ } }