version: 2
jobs:

  build:
    docker: [{ image: 'circleci/node:8.11.1-browsers' }]
    steps:
      - checkout
      - restore_cache: { key: 'npm-packages-{{ checksum "package-lock.json" }}' }
      - npm install
      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths: [ /root/project/node_modules ]
      - ./node_modules/.bin/now --version

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters: { tags: { only: /.*/ } }